# This workflow will publish dist to gh-pages on every push to master branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build and Lint
        run: |
          npm i
          npm run lint

      - name: Recreating gh-pages
        run: |
          cd examples/vue
          npm i
          npm run build
          cd dist
          cp -r ../../../.git .
          git config --local user.email "dipu.sudipta@gmail.com"
          git config --local user.name "dipu-bd"
          git branch -D gh-pages || true
          git checkout -b gh-pages
          git add --all
          git commit -m "[GHA] Update gh-pages"

      - name: Publish changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: examples/vue/dist
